config/routes.rb
ProjectManagement::Application.routes.draw do
  devise_for :users

  resources :projects do
    resources :pages
  end

  root :to => "projects#index" 

end

app/models/page.rb
class Page < ActiveRecord::Base
  validates_presence_of :title

  belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates_presence_of :name

  belongs_to :user
  has_many :pages
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :authenticate_user!

  layout 'application', :except => [:show]
  def new
    @project = Project.find(params[:project_id])
    @page = @project.pages.build
  end

  def create
    @project = Project.find(params[:project_id])
    @page = Page.new(params[:page])
    if @page.save
      redirect_to "/projects/#{@page.project_id}", :notice => "Page added successfully"
    else
      render :action => 'new'
    end
  end

  def edit
    @page = Page.find(params[:id])
    @project = @page.project
  end
   
  def update
    @page = Page.find(params[:id])
    @project = @page.project
    if @page.update_attributes(params[:page])
      redirect_to "/projects/#{@project.id}", :notice => "Page updated successfully"
    else
      render :action => 'edit'
    end
  end

  def show
    @page = Page.find(params[:id])
    render :layout => "content_frame"
  end

  def destroy
    @page = Page.find(params[:id])
    @project = @page.project
    if @page.destroy
      redirect_to "/projects/#{@project.id}", :notice => "Page deleted successfully"
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!
  def index
    @projects = current_user.projects.all   
  end

  def new
    @project = Project.new
  end

  def create
    @project = current_user.projects.build(params[:project])
    if @project.save
      redirect_to "/projects/#{@project.id}", :notice => "Project created successfully"
    else
      render :action => 'new'
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      redirect_to "/projects/#{@project.id}", :notice => "Project updated successfully"
    else
      render :action => 'edit'
    end
  end

  def show
    @project = Project.find(params[:id])
    @pages = @project.pages
  end

  def destroy
    @project = Project.find(params[:id])
    if @project.destroy
      redirect_to projects_path, :notice => "Project deleted successfully"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def build_iframe_code(project, page)
    "<iframe src='#{project_page_url(project, page)}' name='#{page.title}' style='width: 600px; height: 250px'></iframe>"
  end 
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title ProjectManagement
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield :scripts
  %body
    .topbar
      .topbar-inner
        .container
          %h3 
            =link_to "Project Management", root_path
          %ul
            %li.active 
              =link_to "Home", root_path
          %form.pull-left
            =text_field_tag "search", nil, :placeholder=>"Search"
          %ul.nav.secondary-nav
            %li.dropdown(data-dropdown="dropdown")
              - if current_user
                =link_to "Welcome #{current_user.email}", "#", :class=>"dropdown-toggle"
              - else
                =link_to "Welcome Guest", "#"
              %ul.dropdown-menu
                %li=link_to "Sign out", "/users/sign_out", :method=>:delete
 
    .container#page
      #content.row
        #left.span12
          -if notice || alert
            .alert-message
              %p.notice
                =notice
              %p.alert
                =alert
          = yield 

app/views/layouts/content_frame.html.haml
!!!
%html
  %head
    %title Project Management
  %body
    =yield 

app/views/pages/_form.html.haml
= form_for [@project, @page] do |f|
  -if @page.errors.any?
    #errorExplanation
      %h3
        = pluralize(@page.errors.count, "error") 
        prohibited this post from being saved
      %ul
        - @page.errors.full_messages.each do |msg| 
          %li= msg
  .clearfix
    =f.label :title
    .input
      =f.text_field :title, :class => "xlarge"
  .clearfix
    =f.label :content
    .input
      =f.text_area :content, :class => "xlarge"
    .input
      =f.hidden_field :project_id
  .clearfix
    .input
      - if type == 'new'
        =f.submit "Create Page", :class => "btn primary"
      - else
        =f.submit "Update Page", :class => "btn primary" 

app/views/pages/edit.html.haml
.row
  .page_form.span6
    %h2 Update Page
    = render :partial => 'form', :locals => {:type => 'edit'}
  .page_preview.span6
    %h2 Preview
    .content_preview

app/views/pages/new.html.haml
.row
  .page_form.span6
    %h2 Add New Page
    = render :partial => 'form', :locals => {:type => 'new'}
  .page_preview.span6
    %h2 Preview
    .content_preview

app/views/pages/show.html.haml
.content
  =raw @page.content

app/views/projects/_form.html.haml
= form_for @project do |f|
  -if @project.errors.any?
    #errorExplanation
      %h3
        = pluralize(@project.errors.count, "error") 
        prohibited this post from being saved
      %ul
        - @project.errors.full_messages.each do |msg| 
          %li= msg
  .clearfix
    =f.label :name
    .input
      =f.text_field :name, :class => "xlarge"
  .clearfix
    =f.label :description
    .input
      =f.text_area :description, :class => "xlarge"
  .clearfix
    .input
      - if type == 'new'
        =f.submit "Create Project", :class => "btn primary"
      - else
        =f.submit "Update Project", :class => "btn primary"

app/views/projects/edit.html.haml
.project_form
  %h2 Update Project
  = render :partial => 'form', :locals => {:type => 'edit'}

app/views/projects/index.html.haml
.head
  %h1 My Projects
  =link_to 'New project', new_project_path, :class => 'btn primary create_project'
%br
%hr

.projects
  - if @projects.present?
    - @projects.each do |project|
      .project
        %span.controls
          = link_to new_project_page_path(project), :title => "Add pages" do
            = image_tag 'page.png', :size => "20x20"
          = link_to edit_project_path(project), :title => "Edit project" do
            = image_tag 'pencil.png', :size => "20x20"
          = link_to project, :method => 'delete', :confirm => 'This project will be deleted permanently. Do you wish to continue?', :title => "Delete project" do
            = image_tag 'trash.png', :size => "20x20"
        %h2= link_to project.name, "/projects/#{project.id}", :class => 'project_name'
      %hr
      %br 

app/views/projects/new.html.haml
.project_form
  %h2 Create New Project
  = render :partial => 'form', :locals => {:type => 'new'}

app/views/projects/show.html.haml
- content_for :scripts do
  :javascript
    $(document).ready(function(){
      $(".view_page").click(function(){
        $("#page-"+ $(this).attr('id')).toggle("fast");
        return false;
      });
    });

.project_details
  %span.controls
    = link_to "Add page(s)", new_project_page_path(@project), :class => "btn"
    = link_to "Edit", edit_project_path(@project), :class => "btn"
    = link_to "Delete", @project, :method => 'delete', :confirm => 'This project will be deleted permanently. Do you wish to continue?', :class => "btn"
  %h1= @project.name
  %hr
  %p.description
    = @project.description

.pages
  - if @pages.present?
    = link_to "Add page", new_project_page_path(@project), :class => "btn add_page"
    %h2 Pages
    %hr
    - @pages.each do |page|
      .controls
        = link_to edit_project_page_path(@project, page), :title => "Edit page" do
          = image_tag 'pencil.png', :size => "15x15"
        = link_to [@project, page], :method => 'delete', :confirm => "This page will be deleted permanently. Do you wish to continue?", :title => "Delete page" do
          = image_tag 'trash.png', :size => "15x15"
      .page
        %h3= link_to page.title, "#", :id => page.id, :class => "view_page"
        .content_frame{:id => "page-#{page.id}"}
          %iframe{:src=>project_page_url(@project, page), :name=>"#{page.title}", :style=>"width: 600px; height: 250px; display: block"}
          %br
          .clearfix
            = label_tag "Embed Code"
            .input
              = text_area_tag "page_url", build_iframe_code(@project, page), :readonly=>true, :class => "xlarge" 